log_level: 1

ui:
  fps: 60
  dpi: 96
  width: 1000
  height: 700
  grid_size: 25

game:
  title: 'Antsy'
  fullscreen: false
  resizable: true
  vsync: true
  antialiasing: true
  show_fps: false
  show_profiler: false
  show_stats: false
  show_log: false
  show_console: false
  show_cursor: true
  show_cursor_on_focus: true
